const DEFAULT_AUTH_MECHANISM = "DEFAULT";
const MONGODB_CR_AUTH_MECHANISM = "MONGODB-CR";
const SCRAM_SHA_1_AUTH_MECHANISM = "SCRAM-SHA-1";
const SCRAM_SHA_256_AUTH_MECHANISM = "SCRAM-SHA-256";
const PRIMARY_READ_PREFERENCE = "primary";
const PRIMARY_PREFERRED_READ_PREFERENCE = "primaryPreferred";
const SECONDARY_READ_PREFERENCE = "secondary";
const SECONDARY_PREFERRED_READ_PREFERENCE = "secondaryPreferred";
const NEAREST_READ_PREFERENCE = "nearest";


const constants = {
  DEFAULT_AUTH_MECHANISM,
  MONGODB_CR_AUTH_MECHANISM,
  SCRAM_SHA_1_AUTH_MECHANISM,
  SCRAM_SHA_256_AUTH_MECHANISM,
  ALL_AUTH_MECHANISMS: [DEFAULT_AUTH_MECHANISM, MONGODB_CR_AUTH_MECHANISM, SCRAM_SHA_1_AUTH_MECHANISM, SCRAM_SHA_256_AUTH_MECHANISM],

  PRIMARY_READ_PREFERENCE,
  PRIMARY_PREFERRED_READ_PREFERENCE,
  SECONDARY_READ_PREFERENCE,
  SECONDARY_PREFERRED_READ_PREFERENCE,
  NEAREST_READ_PREFERENCE,
  ALL_READ_PREFERENCES: [PRIMARY_READ_PREFERENCE, PRIMARY_PREFERRED_READ_PREFERENCE, SECONDARY_READ_PREFERENCE,
    SECONDARY_PREFERRED_READ_PREFERENCE, NEAREST_READ_PREFERENCE]
};


module.exports = constants;
